target-version = "py312"

line-length = 100

exclude = [
    ".cache",
    ".git",
    ".pypy_cache",
    ".ruff_cache",
    "__pypackages__",
    "venv",
]

[lint]
select = [
    "E",   # pycodestyle err
    "W",   # pycodestyle warn
    "F",   # Pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "RUF", # ruff specific
]

ignore = [
    "D100",
    "D103",
]

fixable = ["ALL"]
unfixable = []

[lint.isort]
known-first-party = ["gen"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]

[lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Depends", "fastapi.Query", "argparse.ArgumentParser"]

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false
