---
- Widgets:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          showTime: true
          timezone: {{ TIMEZONE }}

- Local services:

    - VERT.sh:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vert.svg
        href: http://{{ HOMELAB_ADDRESS }}:3333/
        description: File convert

    - Grafana:
        icon: grafana.svg
        href: http://{{ HOMELAB_ADDRESS }}:3000/
        description: Grafana on local server
        widget:
          type: grafana
          url: http://{{ HOMELAB_ADDRESS }}:3000
          username: {{ GRAFANA_USER }}
          password: {{ GRAFANA_PASSWORD }}

    - Portainer:
        icon: portainer.svg
        href: http://{{ HOMELAB_ADDRESS }}:9000/
        description: Portainer on local server
        widget:
          type: portainer
          url: https://{{ HOMELAB_ADDRESS }}:9443
          env: {{ PORTAINER_ENV }}
          key: {{ PORTAINER_KEY }}

    - Tailscale:
        icon: tailscale.svg
        href: {{ TAILSCALE_HREF }}
        description: Managing Tailscale connections
        # widget:
        #   type: tailscale
        #   address: {{ TAILSCALE_API }}
        #   deviceid: deviceid
        #   key: {{ TAILSCALE_KEY }}

- Design:
    - VERT.sh:
        href: http://{{ HOMELAB_ADDRESS }}:3333
        description: File convert

- Development:
    - VERT.sh:
        href: http://{{ HOMELAB_ADDRESS }}:3333
        description: File convert
