---
- Widgets:
    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          showTime: true
          timezone: {{ TIMEZONE }}

- Local services:

    - VERT.sh:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vert.svg
        description: File convert
        href: http://{{ HOMELAB_ADDRESS }}:{{ VERT_PORT }}/
        siteMonitor: http://{{ HOMELAB_ADDRESS }}:{{ VERT_PORT }}/
        server: {{ DOCKER_NAME }}
        showStats: true
        container: {{ VERT_NAME }}

    - IT-Tools:
        icon: it-tools.svg
        description: Most used IT-Tools
        href: http://{{ HOMELAB_ADDRESS }}:{{ IT_TOOLS_PORT }}/
        siteMonitor: http://{{ HOMELAB_ADDRESS }}:{{ IT_TOOLS_PORT }}/
        server: {{ DOCKER_NAME }}
        showStats: true
        container: {{ IT_TOOLS_NAME }}

    - Grafana:
        icon: grafana.svg
        description: Grafana on local server
        href: http://{{ HOMELAB_ADDRESS }}:{{ GRAFANA_PORT }}/
        siteMonitor: http://{{ HOMELAB_ADDRESS }}:{{ GRAFANA_PORT }}/
        server: {{ DOCKER_NAME }}
        container: {{ GRAFANA_NAME }}
        widget:
          type: grafana
          url: http://{{ HOMELAB_ADDRESS }}:{{ GRAFANA_PORT }}
          username: {{ GRAFANA_USER }}
          password: {{ GRAFANA_PASSWORD }}

    - Portainer:
        icon: portainer.svg
        description: Portainer on local server
        href: http://{{ HOMELAB_ADDRESS }}:{{ PORTAINER_PORT_UI }}/
        siteMonitor: http://{{ HOMELAB_ADDRESS }}:{{ PORTAINER_PORT_UI }}/
        server: {{ DOCKER_NAME }}
        container: {{ PORTAINER_NAME }}
        widget:
          type: portainer
          url: https://{{ HOMELAB_ADDRESS }}:{{ PORTAINER_PORT_API }}
          env: {{ PORTAINER_ENV }}
          key: {{ PORTAINER_KEY }}

    - Homepage:
        icon: homepage
        description: Homepage on local server
        href: http://{{ HOMELAB_ADDRESS }}:{{ HOMEPAGE_PORT }}/
        siteMonitor: http://{{ HOMELAB_ADDRESS }}:{{ HOMEPAGE_PORT }}/
        showStats: true
        server: {{ DOCKER_NAME }}
        container: {{ HOMEPAGE_NAME }}

    # - Tailscale:
    #     icon: tailscale.svg
    #     href: {{ TAILSCALE_HREF }}
    #     description: Managing Tailscale connections
    #     widget:
    #       type: tailscale
    #       address: {{ TAILSCALE_API }}
    #       deviceid: deviceid
    #       key: {{ TAILSCALE_KEY }}

- Design:

    - VERT.sh:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vert.svg
        description: File convert
        href: http://{{ HOMELAB_ADDRESS }}:{{ VERT_PORT }}/
        siteMonitor: http://{{ HOMELAB_ADDRESS }}:{{ VERT_PORT }}/
        server: {{ DOCKER_NAME }}
        showStats: true
        container: {{ VERT_NAME }}

- Development:

    - Github:
        icon: github.svg
        description: github.com
        href: http://github.com/{{ GITHUB_USERNAME }}

    - Gitlab:
        icon: gitlab.svg
        description: gitlab.com
        href: http://gitlab.com/{{ GITLAB_USERNAME }}
