---
- Widgets:

    - Homepage:
        icon: homepage
        description: Homepage on local server
        href: http://{{ HOMELAB_ADDRESS }}:{{ HOMEPAGE_PORT }}/
        statusStyle: dot
        server: {{ DOCKER_NAME }}
        container: {{ HOMEPAGE_NAME }}

    - Watchtower:
        icon: watchtower.svg
        description: Watchtower on local server
        server: {{ DOCKER_NAME }}
        container: {{ WATCHTOWER_NAME }}
        statusStyle: dot
        widget:
          type: watchtower
          url: http://{{ WATCHTOWER_HOSTNAME }}:8080/
          key: {{ WATCHTOWER_KEY }}

    - Calendar:
        widget:
          type: calendar
          firstDayInWeek: monday
          view: monthly
          showTime: true
          timezone: {{ TIMEZONE }}

- Local services:

    - VERT.sh:
        icon: https://cdn.jsdelivr.net/gh/selfhst/icons/svg/vert.svg
        description: File convert
        href: http://{{ HOMELAB_ADDRESS }}:{{ VERT_PORT }}/
        siteMonitor: http://{{ VERT_HOSTNAME }}:80/
        server: {{ DOCKER_NAME }}
        showStats: true
        container: {{ VERT_NAME }}

    - IT-Tools:
        icon: it-tools.svg
        description: Most used IT-Tools
        href: http://{{ HOMELAB_ADDRESS }}:{{ IT_TOOLS_PORT }}/
        siteMonitor: http://{{ IT_TOOLS_HOSTNAME }}:80/
        server: {{ DOCKER_NAME }}
        showStats: true
        container: {{ IT_TOOLS_NAME }}

    - Grafana:
        icon: grafana.svg
        description: Grafana on local server
        href: http://{{ HOMELAB_ADDRESS }}:{{ GRAFANA_PORT }}/
        siteMonitor: http://{{ GRAFANA_HOSTNAME }}:3000/
        server: {{ DOCKER_NAME }}
        container: {{ GRAFANA_NAME }}
        widget:
          type: grafana
          url: http://{{ GRAFANA_HOSTNAME }}:3000
          username: {{ GF_SECURITY_ADMIN_USER }}
          password: {{ GF_SECURITY_ADMIN_PASSWORD }}

    - Portainer:
        icon: portainer.svg
        description: Portainer on local server
        href: http://{{ HOMELAB_ADDRESS }}:{{ PORTAINER_PORT_UI }}/
        siteMonitor: http://{{ PORTAINER_HOSTNAME }}:9000/
        server: {{ DOCKER_NAME }}
        container: {{ PORTAINER_NAME }}
        widget:
          type: portainer
          url: https://{{ PORTAINER_HOSTNAME }}:9443
          env: {{ PORTAINER_ENV }}
          key: {{ PORTAINER_KEY }}

- Design:

    - Figma:
        icon: figma.svg
        description: >
          Cloud-based digital design and collaboration platform
          primarily used for UX/UI.
        href: https://figma.com/

- Development:

    - Github:
        icon: github.svg
        description: github.com
        href: http://github.com/{{ GITHUB_USERNAME }}

    - Gitlab:
        icon: gitlab.svg
        description: gitlab.com
        href: http://gitlab.com/{{ GITLAB_USERNAME }}
