---

- logo:
    icon: https://cdn.jsdelivr.net/npm/@lobehub/icons-static-png@latest/dark/github.png
    href: http://github.com/Kaboupi/homepage-config
    target: _blank

# CPU
- resources:
    cpu: true
    cputemp: true
    units: metric
    tempmin: 0
    tempmax: 100
    network: true

# Memory
- resources:
    memory: true

# Disk
- resources:
    disk: /

- search:
    provider: custom
    url: https://ya.ru/search?text=
    target: _blank
    showSearchSuggestions: true

- datetime:
    text_size: xl
    format:
      timeStyle: short
      hourCycle: h23

- openmeteo:
    href: "https://yandex.ru/pogoda/ru/moscow/maps/nowcast"
    label: {{ LOCATION_NAME }}
    latitude: {{ LOCATION_LATITUDE }}
    longitude: {{ LOCATION_LONGITUDE }}
    timezone: {{ TIMEZONE }}
    units: metric
    cache: 5

